#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE  ]] && set -x

APP="$2"
SCRIPT_PATH="$DOKKU_ROOT/$APP/PREBUILDSCRIPT"

# remove with dokku 0.3.18
verify_app_name() {
  local APP="$1"
  [[ ! -n "$APP" ]] && dokku_log_fail "(verify_app_name) APP must not be null"
  [[ ! -d "$DOKKU_ROOT/$APP" ]] && dokku_log_fail "App $APP does not exist"
  IMAGE="dokku/$APP"
  return 0
}

check_exists() {
  [[ ! -f "$SCRIPT_PATH" ]] && echo "No prebuild script configured for $APP" && exit 1
}
